repository_type: pipeline

nf_core_version: 4.0.1

lint:
  files_unchanged:
    - LICENSE
    - .github/PULL_REQUEST_TEMPLATE.md
    - docs/CONTRIBUTING.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-smallrnaseq_logo_light.png
    - docs/images/nf-core-smallrnaseq_logo_light.png
    - docs/images/nf-core-smallrnaseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
  nextflow_config: false
  nf_test_content: false
  multiqc_config:
    - report_comment
  files_exist:
    - LICENSE
    - conf/test.config
    - conf/test_full.config
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - CODE_OF_CONDUCT.md
    - assets/nf-core-smallrnaseq_logo_light.png
    - docs/images/nf-core-smallrnaseq_logo_light.png
    - docs/images/nf-core-smallrnaseq_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CHANGELOG.md

template:
  org: nf
  name: smallrnaseq
  description: Test
  author: APAF
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - changelog
    - license
    - test_config
    - nf-test
    - igenomes
    - seqera_platform
    - codespaces
    - vscode
    - rocrate
    - email
  is_nfcore: false
